ALTER TABLE "CompanyProfile"
  ADD COLUMN IF NOT EXISTS "company_bio" TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "location" TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "industry" TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "twitter_url" TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "is_verified" BOOLEAN DEFAULT FALSE;
